apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-xijg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-xijg
    app.kubernetes.io/part-of: build-suite-test-application-swif
  name: test-component-pac-xijg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-component-pac-xijg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-component-pac-xijg
    spec:
      containers:
      - image: quay.io/pkumari_org/build-e2e-hvcr-tenant/build-suite-test-application-swif/test-component-pac-xijg@sha256:d7d8ad610c6eadd1e0506475eb774c4c9bb673bb8dbd862cc6fbd53915594139
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
